source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

project 'SDWebImage Tests'
workspace '../SDWebImage'

target 'Tests' do
  platform :ios, '8.0'
  pod 'Expecta'
  pod 'SDWebImage/WebP', :path => '../'
  pod 'SDWebImage/MapKit', :path => '../'
  pod 'SDWebImage/GIF', :path => '../'
  pod 'SDWebImage/SVG', :path => '../'
  pod 'SVGKit', :git => 'https://github.com/SVGKit/SVGKit.git', :branch => '2.x'

end
